# Generated by Django 6.0.1 on 2026-02-02 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=11)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ALUGADO', 'Alugado')], max_length=20)),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locatario', to='api.usuario')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locador', to='api.usuario')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='api.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('status', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api.contrato')),
            ],
        ),
    ]
